# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
	scan(
	     workspace: "SHOP.workspace"
	     devices: ["iPhone 11"]
		)
  end
end

platform :ios do
  desc "Description of what the lane does"
  lane :upload do
	pilot(
	     workspace: "SHOP.workspace"
	     devices: ["iPhone 11"]
		)
  end
end

clear_derived_data(derived_data_path: "/Users/andreyrachitsky/Library/Developer/Xcode/DerivedData")

platform :ios do
  desc "Description of what the lane does"
  lane :project do
	gym(
	     scheme: "SHOP",
       configuration: "Debug",
       export_method: "development",
       include_symbols: true,
       include_bitcode: true,
       silent: false
		)
  end
end
